id: A1EDD6568
title: 'Opening the Door to a Pure Realm: An Aspiration Towards Abhirati'
type: translation
pechas:
- I3A5A2AAC
- ID68DEE03
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:47:36.899698
  last_modified_at: 2023-01-04 12:47:36.899704
  collections:
  - Katok Situ Chökyi Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  I3A5A2AAC/5C2F: 4AB8
  ID68DEE03/0CB2: 4AB8
